// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from "@hey-api/client-fetch";
import type {
  RunPipelinePipelinesRunPostData,
  RunPipelinePipelinesRunPostResponses,
  RunPipelinePipelinesRunPostErrors,
  GetPipelineStatusPipelineStatusGetData,
  GetPipelineStatusPipelineStatusGetResponses,
  GetPipelineStatusPipelineStatusGetErrors,
  GetPipelinesPipelinesGetData,
  GetPipelinesPipelinesGetResponses,
  GetFilteredPipelinesPipelinesFilterGetData,
  GetFilteredPipelinesPipelinesFilterGetResponses,
  GetFilteredPipelinesPipelinesFilterGetErrors,
  GetPresignedUrlPresignedUrlGetData,
  GetPresignedUrlPresignedUrlGetResponses,
  GetPresignedUrlPresignedUrlGetErrors,
  CreateDatasetDatasetsCreatePostData,
  CreateDatasetDatasetsCreatePostResponses,
  CreateDatasetDatasetsCreatePostErrors,
  ExtractCsvDatasetsExtractPostData,
  ExtractCsvDatasetsExtractPostResponses,
  ExtractCsvDatasetsExtractPostErrors,
  GetDatasetColumnsDatasetsColumnsGetData,
  GetDatasetColumnsDatasetsColumnsGetResponses,
  GetDatasetColumnsDatasetsColumnsGetErrors,
  EditDatasetDatasetsDatasetIdEditPutData,
  EditDatasetDatasetsDatasetIdEditPutResponses,
  EditDatasetDatasetsDatasetIdEditPutErrors,
  DeleteDatasetDatasetsDatasetIdDeleteData,
  DeleteDatasetDatasetsDatasetIdDeleteResponses,
  DeleteDatasetDatasetsDatasetIdDeleteErrors,
  GetDatasetsDatasetsGetData,
  GetDatasetsDatasetsGetResponses,
  GetDatasetInfoDatasetGetData,
  GetDatasetInfoDatasetGetResponses,
  GetDatasetInfoDatasetGetErrors,
  GetUserDatasetsUserDatasetsGetData,
  GetUserDatasetsUserDatasetsGetResponses,
  GetUserDatasetsUserDatasetsGetErrors,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Run Pipeline
 */
export const runPipelinePipelinesRunPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RunPipelinePipelinesRunPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RunPipelinePipelinesRunPostResponses,
    RunPipelinePipelinesRunPostErrors,
    ThrowOnError
  >({
    url: "/pipelines/run",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Pipeline Status
 */
export const getPipelineStatusPipelineStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPipelineStatusPipelineStatusGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPipelineStatusPipelineStatusGetResponses,
    GetPipelineStatusPipelineStatusGetErrors,
    ThrowOnError
  >({
    url: "/pipeline/status",
    ...options,
  });
};

/**
 * Get Pipelines
 */
export const getPipelinesPipelinesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPipelinesPipelinesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetPipelinesPipelinesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/pipelines",
    ...options,
  });
};

/**
 * Get Filtered Pipelines
 */
export const getFilteredPipelinesPipelinesFilterGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFilteredPipelinesPipelinesFilterGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetFilteredPipelinesPipelinesFilterGetResponses,
    GetFilteredPipelinesPipelinesFilterGetErrors,
    ThrowOnError
  >({
    url: "/pipelines/filter",
    ...options,
  });
};

/**
 * Get Presigned Url
 */
export const getPresignedUrlPresignedUrlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPresignedUrlPresignedUrlGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPresignedUrlPresignedUrlGetResponses,
    GetPresignedUrlPresignedUrlGetErrors,
    ThrowOnError
  >({
    url: "/presignedURL",
    ...options,
  });
};

/**
 * Create Dataset
 */
export const createDatasetDatasetsCreatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDatasetDatasetsCreatePostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDatasetDatasetsCreatePostResponses,
    CreateDatasetDatasetsCreatePostErrors,
    ThrowOnError
  >({
    url: "/datasets/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Extract Csv
 */
export const extractCsvDatasetsExtractPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExtractCsvDatasetsExtractPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ExtractCsvDatasetsExtractPostResponses,
    ExtractCsvDatasetsExtractPostErrors,
    ThrowOnError
  >({
    url: "/datasets/extract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Dataset Columns
 */
export const getDatasetColumnsDatasetsColumnsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetDatasetColumnsDatasetsColumnsGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDatasetColumnsDatasetsColumnsGetResponses,
    GetDatasetColumnsDatasetsColumnsGetErrors,
    ThrowOnError
  >({
    url: "/datasets/columns",
    ...options,
  });
};

/**
 * Edit Dataset
 */
export const editDatasetDatasetsDatasetIdEditPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EditDatasetDatasetsDatasetIdEditPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    EditDatasetDatasetsDatasetIdEditPutResponses,
    EditDatasetDatasetsDatasetIdEditPutErrors,
    ThrowOnError
  >({
    url: "/datasets/{dataset_id}/edit",
    ...options,
  });
};

/**
 * Delete Dataset
 */
export const deleteDatasetDatasetsDatasetIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDatasetDatasetsDatasetIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDatasetDatasetsDatasetIdDeleteResponses,
    DeleteDatasetDatasetsDatasetIdDeleteErrors,
    ThrowOnError
  >({
    url: "/datasets/{dataset_id}",
    ...options,
  });
};

/**
 * Get Datasets
 */
export const getDatasetsDatasetsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetDatasetsDatasetsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetDatasetsDatasetsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/datasets",
    ...options,
  });
};

/**
 * Get Dataset Info
 */
export const getDatasetInfoDatasetGet = <ThrowOnError extends boolean = false>(
  options: Options<GetDatasetInfoDatasetGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDatasetInfoDatasetGetResponses,
    GetDatasetInfoDatasetGetErrors,
    ThrowOnError
  >({
    url: "/dataset",
    ...options,
  });
};

/**
 * Get User Datasets
 */
export const getUserDatasetsUserDatasetsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserDatasetsUserDatasetsGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserDatasetsUserDatasetsGetResponses,
    GetUserDatasetsUserDatasetsGetErrors,
    ThrowOnError
  >({
    url: "/user/datasets",
    ...options,
  });
};
